version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ror_books_dev
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ror_books_dev"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      RAILS_ENV: development
      DATABASE_URL_DEV: postgresql://postgres:postgres@db:5432/ror_books_dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle-cache:/usr/local/bundle
    command: bash -lc "bundle check || bundle install && (bin/rails db:prepare || true) && bin/rails server -b 0.0.0.0 -p 3000"

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    environment:
      - VITE_API_BASE_URL=http://localhost:3000
    ports:
      - "5173:5173"
    command: sh -lc "npm ci || npm i && npm run dev -- --host"

volumes:
  db-data:
  bundle-cache:


